name: Stock Auto Update
on:
  schedule:
    # 07:00 UTC = 15:00 Taiwan Time (GMT+8)
    # Chạy từ thứ 2 đến thứ 6 hàng tuần
    - cron: '0 7 * * 1-5'
  workflow_dispatch: # Cho phép bạn bấm nút chạy thủ công bất cứ lúc nào

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Quan trọng: Cho phép Bot đẩy file Excel ngược lại Repo

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install pandas yfinance openpyxl

    - name: Run Scan Script
      run: |
        python stock_tw.py
        python dashboard_tw_vn.py

    - name: Commit and Push changes
      run: |
        git config --global user.name 'Github-Action-Bot'
        git config --global user.email 'actions@github.com'
        git add *.xlsx
        git commit -m "Auto-update TW Market Data: $(date)" || echo "No changes to commit"
        git push